manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: perillamint
      url-base: https://github.com/perillamint
  projects:
    - name: zmk
      remote: perillamint
      revision: charybdis-pmw3610
      import: app/west.yml
  self:
    path: config