name: Build

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    strategy:
      fail-fast: false
      matrix:
        include:
          # Splinky v2
          - board: nice_nano_v2
            shield: splinky_v2_left
          - board: nice_nano_v2
            shield: splinky_v2_right
          # Splinky v3
          - board: nice_nano_v2
            shield: splinky_v3_left
          - board: nice_nano_v2
            shield: splinky_v3_right
          # Settings reset
          - board: nice_nano_v2
            shield: settings_reset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Shield Files
        run: |
          # Create shield directories
          mkdir -p config/boards/shields/splinky_v2
          mkdir -p config/boards/shields/splinky_v3
          
          # Copy shield files from repository root if they exist
          find config -maxdepth 1 -name "*.dtsi" -o -name "*.overlay" -o -name "Kconfig.*" | while read file; do
            filename=$(basename "$file")
            case "$filename" in
              splinky_v2*.dtsi|splinky_v2*.overlay)
                cp "$file" "config/boards/shields/splinky_v2/"
                echo "Copied $file to config/boards/shields/splinky_v2/"
                ;;
              splinky_v3*.dtsi|splinky_v3*.overlay)
                cp "$file" "config/boards/shields/splinky_v3/"
                echo "Copied $file to config/boards/shields/splinky_v3/"
                ;;
              Kconfig.*)
                cp "$file" "config/boards/shields/splinky_v2/"
                cp "$file" "config/boards/shields/splinky_v3/"
                echo "Copied $file to both shield directories"
                ;;
            esac
          done
          
          # Copy keymap file if it exists
          if [ -f "config/charybdis.keymap" ]; then
            cp "config/charybdis.keymap" "config/splinky_v2.keymap"
            cp "config/charybdis.keymap" "config/splinky_v3.keymap"
            echo "Copied keymap file"
          fi
          
          # List shield files
          echo "Shield files found:"
          find config/boards/shields -type f | sort
          
      - name: Initialize ZMK
        run: |
          # Create zmk directory
          mkdir -p zmk
          cd zmk
          
          # Use curl instead of git clone
          echo "Downloading ZMK repository archive..."
          curl -L https://github.com/perillamint/zmk/archive/refs/heads/charybdis-pmw3610.zip -o zmk.zip
          unzip zmk.zip
          mv zmk-charybdis-pmw3610/* .
          rmdir zmk-charybdis-pmw3610
          
          # Verify download
          ls -la
          
      - name: Build Firmware
        run: |
          # Set ZMK_CONFIG environment variable
          export ZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          cd zmk
          
          # Initialize west
          west init -l app
          west update
          
          # Build
          west build -d build -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${ZMK_CONFIG}"
          
          # Check build result
          if [ -f "build/zephyr/zmk.uf2" ]; then
            mkdir -p "${GITHUB_WORKSPACE}/artifacts"
            cp build/zephyr/zmk.uf2 "${GITHUB_WORKSPACE}/artifacts/${{ matrix.shield }}.uf2"
            echo "Build successful for ${{ matrix.shield }}"
          else
            echo "Build failed for ${{ matrix.shield }}"
            exit 1
          fi
          
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/*.uf2
          
      - name: Archive Build Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.shield }}
          path: |
            zmk/build/zephyr/*.log
            zmk/build/CMakeFiles/CMakeError.log
            zmk/build/CMakeFiles/CMakeOutput.log