name: Build

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    strategy:
      fail-fast: false
      matrix:
        include:
          # Splinky v2
          - board: nice_nano_v2
            shield: splinky_v2_left
          - board: nice_nano_v2
            shield: splinky_v2_right
          # Splinky v3
          - board: nice_nano_v2
            shield: splinky_v3_left
          - board: nice_nano_v2
            shield: splinky_v3_right
          # Settings reset
          - board: nice_nano_v2
            shield: settings_reset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: West Init
        run: west init -l config
        
      - name: Configure Git
        run: |
          git config --global --add safe.directory '*'
          git config --global url."https://github.com/".insteadOf git://github.com/
          
      - name: Setup Shield Files
        run: |
          # Create shield directories
          mkdir -p config/boards/shields/splinky_v2
          mkdir -p config/boards/shields/splinky_v3
          
          # Copy existing shield files if they exist
          if [ -f "config/splinky_v2.dtsi" ]; then
            cp "config/splinky_v2.dtsi" "config/boards/shields/splinky_v2/splinky_v2.dtsi"
          fi
          
          if [ -f "config/splinky_v2_left.overlay" ]; then
            cp "config/splinky_v2_left.overlay" "config/boards/shields/splinky_v2/splinky_v2_left.overlay"
          fi
          
          if [ -f "config/splinky_v2_right.overlay" ]; then
            cp "config/splinky_v2_right.overlay" "config/boards/shields/splinky_v2/splinky_v2_right.overlay"
          fi
          
          if [ -f "config/Kconfig.defconfig" ]; then
            cp "config/Kconfig.defconfig" "config/boards/shields/splinky_v2/Kconfig.defconfig"
          fi
          
          if [ -f "config/Kconfig.shield" ]; then
            cp "config/Kconfig.shield" "config/boards/shields/splinky_v2/Kconfig.shield"
          fi
          
          # Copy keymap files if needed
          if [ -f "config/charybdis.keymap" ]; then
            cp "config/charybdis.keymap" "config/splinky_v2.keymap"
            cp "config/charybdis.keymap" "config/splinky_v3.keymap"
          fi
          
          # List shield files
          echo "Shield files found:"
          find config/boards/shields -type f | sort
          
      - name: Clone ZMK Repository
        run: |
          # Direct clone instead of west update to avoid authentication issues
          git clone --single-branch --branch charybdis-pmw3610 --depth 1 https://github.com/perillamint/zmk.git
          
      - name: West Build (${{ matrix.board }} - ${{ matrix.shield }})
        run: |
          # Set ZMK_CONFIG environment variable
          export ZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          cd zmk
          west init -l app
          west update
          cd app
          west build -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
          
          # Check and move build artifacts
          if [ -f "build/zephyr/zmk.uf2" ]; then
            mkdir -p "${GITHUB_WORKSPACE}/artifacts"
            cp build/zephyr/zmk.uf2 "${GITHUB_WORKSPACE}/artifacts/${{ matrix.shield }}.uf2"
            echo "Build successful for ${{ matrix.shield }}"
          else
            echo "Build failed for ${{ matrix.shield }}"
            exit 1
          fi
          
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/*.uf2
          
      - name: Archive Build Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.shield }}
          path: |
            zmk/app/build/zephyr/*.log
            zmk/app/build/CMakeFiles/CMakeError.log
            zmk/app/build/CMakeFiles/CMakeOutput.log