name: Build

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'config/**'
      - '.github/workflows/build.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    strategy:
      fail-fast: false
      matrix:
        include:
          # Splinky v2
          - board: nice_nano_v2
            shield: splinky_v2_left
          - board: nice_nano_v2
            shield: splinky_v2_right
          # Splinky v3
          - board: nice_nano_v2
            shield: splinky_v3_left
          - board: nice_nano_v2
            shield: splinky_v3_right
          # Settings reset
          - board: nice_nano_v2
            shield: settings_reset
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cache west modules
        uses: actions/cache@v4
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: West Init
        run: west init -l config
        
      - name: Configure Git
        run: |
          git config --global --add safe.directory '*'
          git config --global url."https://github.com/".insteadOf git://github.com/
          
      - name: Setup Shield Files
        run: |
          # Create shield directories
          mkdir -p config/boards/shields/splinky_v2
          mkdir -p config/boards/shields/splinky_v3
          
          # Copy existing shield files if they exist
          if [ -f "config/splinky_v2.dtsi" ]; then
            cp "config/splinky_v2.dtsi" "config/boards/shields/splinky_v2/splinky_v2.dtsi"
          fi
          
          if [ -f "config/splinky_v2_left.overlay" ]; then
            cp "config/splinky_v2_left.overlay" "config/boards/shields/splinky_v2/splinky_v2_left.overlay"
          fi
          
          if [ -f "config/splinky_v2_right.overlay" ]; then
            cp "config/splinky_v2_right.overlay" "config/boards/shields/splinky_v2/splinky_v2_right.overlay"
          fi
          
          if [ -f "config/Kconfig.defconfig" ]; then
            cp "config/Kconfig.defconfig" "config/boards/shields/splinky_v2/Kconfig.defconfig"
          fi
          
          if [ -f "config/Kconfig.shield" ]; then
            cp "config/Kconfig.shield" "config/boards/shields/splinky_v2/Kconfig.shield"
          fi
          
          # Copy keymap files if needed
          if [ -f "config/charybdis.keymap" ]; then
            cp "config/charybdis.keymap" "config/splinky_v2.keymap"
            cp "config/charybdis.keymap" "config/splinky_v3.keymap"
          fi
          
          # Verify shield files exist
          for file in "config/boards/shields/splinky_v2/splinky_v2.dtsi" \
                     "config/boards/shields/splinky_v2/splinky_v2_left.overlay" \
                     "config/boards/shields/splinky_v2/splinky_v2_right.overlay" \
                     "config/boards/shields/splinky_v2/Kconfig.defconfig" \
                     "config/boards/shields/splinky_v2/Kconfig.shield" \
                     "config/boards/shields/splinky_v3/splinky_v3.dtsi" \
                     "config/boards/shields/splinky_v3/splinky_v3_left.overlay" \
                     "config/boards/shields/splinky_v3/splinky_v3_right.overlay" \
                     "config/boards/shields/splinky_v3/Kconfig.defconfig" \
                     "config/boards/shields/splinky_v3/Kconfig.shield"; do
            if [ ! -f "$file" ]; then
              echo "ERROR: Required file $file is missing!"
              echo "Please add the file to your repository."
            fi
          done
          
          # List shields files that were found
          echo "Shield files found:"
          find config/boards/shields -type f | sort
          
      - name: West Update
        run: |
          # Set environment variable to prevent authentication prompt
          export GIT_TERMINAL_PROMPT=0
          west update -o=--depth=1 || true
          
          # Check if update failed and use direct clone as a fallback
          if [ ! -d "zmk" ]; then
            echo "West update failed, trying direct clone..."
            mkdir -p zmk
            cd zmk
            git init
            git remote add origin https://github.com/perillamint/zmk.git
            git fetch --depth 1 origin charybdis-pmw3610
            git checkout FETCH_HEAD
            cd ..
          fi
          
      - name: West Zephyr export
        run: west zephyr-export
        
      - name: West Build (${{ matrix.board }} - ${{ matrix.shield }})
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
        
      - name: Check Build Result
        id: check_build
        run: |
          if [ -f "build/zephyr/zmk.uf2" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Rename artifacts
        if: ${{ steps.check_build.outputs.success == 'true' && matrix.shield != 'settings_reset' }}
        run: |
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 "artifacts/${{ matrix.shield }}.uf2"
          
      - name: Rename artifacts (settings_reset)
        if: ${{ steps.check_build.outputs.success == 'true' && matrix.shield == 'settings_reset' }}
        run: |
          mkdir -p artifacts
          cp build/zephyr/zmk.uf2 "artifacts/settings_reset.uf2"
          
      - name: Archive firmware
        if: ${{ steps.check_build.outputs.success == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: artifacts/*.uf2
          
      - name: Archive Build Logs on Failure
        if: ${{ steps.check_build.outputs.success == 'false' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ matrix.shield }}
          path: |
            build/zephyr/*.log
            build/CMakeFiles/CMakeError.log
            build/CMakeFiles/CMakeOutput.log